export { default as logo } from "../assets/images/logo.svg";
export { default as laptop } from "../assets/images/laptop.png";
export { default as laptopBox } from "../assets/images/laptop-box.png";
export { default as priceTag } from "../assets/images/price-tag.png";
export { default as grid1 } from "../assets/images/grid-one.png";
export { default as grid2 } from "../assets/images/grid-two.png";
export { default as grid3 } from "../assets/images/grid-three.png";
export { default as grid4 } from "../assets/images/grid-four.png";
export { default as grid5 } from "../assets/images/grid-five.png";
export { default as midImag } from "../assets/images/mid-img-laptop.png";
export { default as winProImg } from "../assets/images/windows-laptop.png";
export { default as benImg1 } from "../assets/images/benefits-top.png";
export { default as benImg2 } from "../assets/images/benefits-left-bottom.png";
export { default as benImg3 } from "../assets/images/benefits-right-bottom.png";
export { default as display1 } from "../assets/images/display-1.png";
export { default as book1 } from "../assets/images/book1.png";
export { default as halfLaptop } from "../assets/images/halflaptop.png";
export { default as fooLogo } from "../assets/images/foologo.png";
export { default as certificates } from "../assets/images/cirtificates.png";
export { default as butterflyImg } from "../assets/images/butterflyImg.png";

// export { default as grayImg1 } from "../assets/images/1.png";
// export { default as grayImg2 } from "../assets/images/2.png";
// export { default as grayImg3 } from "../assets/images/3.png";
// export { default as grayImg4 } from "../assets/images/4.png";
// export { default as grayImg5 } from "../assets/images/5.png";
// export { default as grayImg6 } from "../assets/images/6.png";
// export { default as grayImg7 } from "../assets/images/7.png";
